// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9DIUhuvhwhA01g3PGDnAEtDmYFwYlPU',
    appId: '1:526718489563:web:1c1a4bb56d45544ffe0dfe',
    messagingSenderId: '526718489563',
    projectId: 'vitasora-22a61',
    authDomain: 'vitasora-22a61.firebaseapp.com',
    storageBucket: 'vitasora-22a61.firebasestorage.app',
    measurementId: 'G-EEY272HXYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJsD0eQi-RW4-gPNSepnSm3Cx_j1QwHA',
    appId: '1:526718489563:android:2893dc9331a72d7dfe0dfe',
    messagingSenderId: '526718489563',
    projectId: 'vitasora-22a61',
    storageBucket: 'vitasora-22a61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWx1SUbEMGwX5-HOXkYMvEOC1FNyqr56E',
    appId: '1:526718489563:ios:50387fb903a7660afe0dfe',
    messagingSenderId: '526718489563',
    projectId: 'vitasora-22a61',
    storageBucket: 'vitasora-22a61.firebasestorage.app',
    iosClientId: '526718489563-k6auckk76jitkvobdhd72c1mh987vvnh.apps.googleusercontent.com',
    iosBundleId: 'com.VitaSora.vitasora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWx1SUbEMGwX5-HOXkYMvEOC1FNyqr56E',
    appId: '1:526718489563:ios:50387fb903a7660afe0dfe',
    messagingSenderId: '526718489563',
    projectId: 'vitasora-22a61',
    storageBucket: 'vitasora-22a61.firebasestorage.app',
    iosClientId: '526718489563-k6auckk76jitkvobdhd72c1mh987vvnh.apps.googleusercontent.com',
    iosBundleId: 'com.VitaSora.vitasora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT9DIUhuvhwhA01g3PGDnAEtDmYFwYlPU',
    appId: '1:526718489563:web:32872dcfba29f58efe0dfe',
    messagingSenderId: '526718489563',
    projectId: 'vitasora-22a61',
    authDomain: 'vitasora-22a61.firebaseapp.com',
    storageBucket: 'vitasora-22a61.firebasestorage.app',
    measurementId: 'G-WRDL58CX9G',
  );

}